In [51]:
#importing the necessary packages
import numpy as np

#URL Link
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

#Load the dataset from the csv file using numpy
iris = np.genfromtxt(url,delimiter=',',dtype='float')

#Getting the first column of iris's Sepal Length
a = iris[:,:1]

#print(a)
#Calculating the iris's mean
iris_mean = np.mean(a)
print("Mean: ",iris_mean)

#Calculating the iris's median
iris_median = np.median(a)
print("Median: ",iris_median)

#Calculating the iris's standard deviation
iris_standard_deviation = np.std(a)
print("Standard Deviation: ",iris_standard_deviation)

print()
print()

#HomeWork 2

#Getting the columns
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])

#Creating a new Array
filter_arr = []

#Getting the targeted column where b[0] = Sepal Length and b[2] = Petal Length
for element in iris_2d:
  if element[2] > 1.5 and element[0]< 5.0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

#Filtered Array
newArr = iris_2d[filter_arr]
#print(filter_arr)

#
print("Printing the Filtered Array where Petal Length > 1.5 and Sepal Length < 5.0\n",newArr)

Mean:  5.843333333333334
Median:  5.8
Standard Deviation:  0.8253012917851409


Printing the Filtered Array where Petal Length > 1.5 and Sepal Length < 5.0
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]
